/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myMovies;

import java.awt.Color;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/**
 *
 * @author trapatsas
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        EntityManagerFactory entityManager = Persistence.createEntityManagerFactory("MyMoviesProjectPU");
        MovieJpaController movieController = new MovieJpaController(entityManager);
        for (Movie m : movieController.findMovieEntities()) {
          jTextArea2.append(m.getTitle()+ " (" + m.getOverview()+ ")" + "\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        GetMoviesPanel = new javax.swing.JPanel();
        getLabel = new javax.swing.JLabel();
        FavouritePanel = new javax.swing.JPanel();
        favLabel = new javax.swing.JLabel();
        SearchPanel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        StatsPanel = new javax.swing.JPanel();
        statsLabel = new javax.swing.JLabel();
        ExitPanel = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        AboutPanel = new javax.swing.JPanel();
        aboutLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        getDataTabPanel = new javax.swing.JPanel();
        favouriteTabPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        searchTabPanel = new javax.swing.JPanel();
        statsTabPanel = new javax.swing.JPanel();
        aboutTabPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(108, 88, 141));
        setLocationByPlatform(true);

        bgPanel.setBackground(new java.awt.Color(108, 88, 141));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarPanel.setBackground(new java.awt.Color(54, 33, 89));
        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GetMoviesPanel.setBackground(new java.awt.Color(85, 55, 118));

        getLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getLabel.setForeground(new java.awt.Color(255, 255, 255));
        getLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_Data_Transfer_15px_1.png"))); // NOI18N
        getLabel.setLabelFor(GetMoviesPanel);
        getLabel.setText("Ανάκτηση & Αποθήκευση");
        getLabel.setToolTipText(null);
        getLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                getLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                getLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout GetMoviesPanelLayout = new javax.swing.GroupLayout(GetMoviesPanel);
        GetMoviesPanel.setLayout(GetMoviesPanelLayout);
        GetMoviesPanelLayout.setHorizontalGroup(
            GetMoviesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GetMoviesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(96, 96, 96))
        );
        GetMoviesPanelLayout.setVerticalGroup(
            GetMoviesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(getLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sidebarPanel.add(GetMoviesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, 60));

        FavouritePanel.setBackground(new java.awt.Color(85, 55, 118));

        favLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        favLabel.setForeground(new java.awt.Color(255, 255, 255));
        favLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        favLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_Heart_15px.png"))); // NOI18N
        favLabel.setLabelFor(FavouritePanel);
        favLabel.setText("Λίστες Αγαπημένων");
        favLabel.setToolTipText(null);
        favLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                favLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                favLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                favLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout FavouritePanelLayout = new javax.swing.GroupLayout(FavouritePanel);
        FavouritePanel.setLayout(FavouritePanelLayout);
        FavouritePanelLayout.setHorizontalGroup(
            FavouritePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FavouritePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(favLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        FavouritePanelLayout.setVerticalGroup(
            FavouritePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(favLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sidebarPanel.add(FavouritePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 200, 60));

        SearchPanel.setBackground(new java.awt.Color(85, 55, 118));

        searchLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchLabel.setForeground(new java.awt.Color(255, 255, 255));
        searchLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        searchLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_Search_15px.png"))); // NOI18N
        searchLabel.setLabelFor(SearchPanel);
        searchLabel.setText("Αναζήτηση ταινιών");
        searchLabel.setToolTipText(null);
        searchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sidebarPanel.add(SearchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 60));

        StatsPanel.setBackground(new java.awt.Color(85, 55, 118));

        statsLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        statsLabel.setForeground(new java.awt.Color(255, 255, 255));
        statsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_Combo_Chart_15px.png"))); // NOI18N
        statsLabel.setLabelFor(StatsPanel);
        statsLabel.setText("Στατιστικά");
        statsLabel.setToolTipText(null);
        statsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statsLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                statsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                statsLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout StatsPanelLayout = new javax.swing.GroupLayout(StatsPanel);
        StatsPanel.setLayout(StatsPanelLayout);
        StatsPanelLayout.setHorizontalGroup(
            StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        StatsPanelLayout.setVerticalGroup(
            StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sidebarPanel.add(StatsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 200, 60));

        ExitPanel.setBackground(new java.awt.Color(85, 55, 118));

        exitLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        exitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_Shutdown_15px.png"))); // NOI18N
        exitLabel.setLabelFor(ExitPanel);
        exitLabel.setText("Έξοδος");
        exitLabel.setToolTipText(null);
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ExitPanelLayout = new javax.swing.GroupLayout(ExitPanel);
        ExitPanel.setLayout(ExitPanelLayout);
        ExitPanelLayout.setHorizontalGroup(
            ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        ExitPanelLayout.setVerticalGroup(
            ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sidebarPanel.add(ExitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 200, 60));

        AboutPanel.setBackground(new java.awt.Color(85, 55, 118));

        aboutLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aboutLabel.setForeground(new java.awt.Color(255, 255, 255));
        aboutLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        aboutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_About_15px.png"))); // NOI18N
        aboutLabel.setLabelFor(AboutPanel);
        aboutLabel.setText("Σχετικά");
        aboutLabel.setToolTipText(null);
        aboutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout AboutPanelLayout = new javax.swing.GroupLayout(AboutPanel);
        AboutPanel.setLayout(AboutPanelLayout);
        AboutPanelLayout.setHorizontalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        AboutPanelLayout.setVerticalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sidebarPanel.add(AboutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 200, 60));

        jLabel6.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("My Movies");
        sidebarPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_Disney_Movies__100px.png"))); // NOI18N
        jLabel7.setToolTipText("");
        sidebarPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 100, 40));

        bgPanel.add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        topPanel.setBackground(new java.awt.Color(108, 88, 141));
        topPanel.setPreferredSize(new java.awt.Dimension(810, 600));

        HeaderPanel.setBackground(new java.awt.Color(54, 33, 89));

        headerLabel.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(204, 204, 204));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setLabelFor(HeaderPanel);
        headerLabel.setToolTipText(null);

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cardPanel.setBackground(new java.awt.Color(108, 88, 141));
        cardPanel.setLayout(new java.awt.CardLayout());

        getDataTabPanel.setBackground(new java.awt.Color(108, 88, 141));

        javax.swing.GroupLayout getDataTabPanelLayout = new javax.swing.GroupLayout(getDataTabPanel);
        getDataTabPanel.setLayout(getDataTabPanelLayout);
        getDataTabPanelLayout.setHorizontalGroup(
            getDataTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        getDataTabPanelLayout.setVerticalGroup(
            getDataTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        cardPanel.add(getDataTabPanel, "card2");

        favouriteTabPanel.setBackground(new java.awt.Color(108, 88, 141));

        jTextArea2.setBackground(new java.awt.Color(108, 88, 141));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout favouriteTabPanelLayout = new javax.swing.GroupLayout(favouriteTabPanel);
        favouriteTabPanel.setLayout(favouriteTabPanelLayout);
        favouriteTabPanelLayout.setHorizontalGroup(
            favouriteTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(favouriteTabPanelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        favouriteTabPanelLayout.setVerticalGroup(
            favouriteTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, favouriteTabPanelLayout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cardPanel.add(favouriteTabPanel, "card3");

        searchTabPanel.setBackground(new java.awt.Color(108, 88, 141));

        javax.swing.GroupLayout searchTabPanelLayout = new javax.swing.GroupLayout(searchTabPanel);
        searchTabPanel.setLayout(searchTabPanelLayout);
        searchTabPanelLayout.setHorizontalGroup(
            searchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        searchTabPanelLayout.setVerticalGroup(
            searchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        cardPanel.add(searchTabPanel, "card4");

        statsTabPanel.setBackground(new java.awt.Color(108, 88, 141));

        javax.swing.GroupLayout statsTabPanelLayout = new javax.swing.GroupLayout(statsTabPanel);
        statsTabPanel.setLayout(statsTabPanelLayout);
        statsTabPanelLayout.setHorizontalGroup(
            statsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        statsTabPanelLayout.setVerticalGroup(
            statsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        cardPanel.add(statsTabPanel, "card5");

        aboutTabPanel.setBackground(new java.awt.Color(108, 88, 141));
        aboutTabPanel.setForeground(new java.awt.Color(108, 88, 141));
        aboutTabPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jScrollPane1.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(108, 88, 141));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("Η εφαρμογή αυτή δημιουργήθηκε από τους φοιτητές \ni) Παναγιώτη Τραπατσα\nii) Αποστολη Νταλαμπιρα και \niii) Δημήτρη Τομπέα\nστα πλαίσια της 3ης ομαδικής εργασίας για την ΠΛΗ24,\nμε επιβλέπων καθηγητή τον κ. Φιτσιλή Παναγιώτη\n");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout aboutTabPanelLayout = new javax.swing.GroupLayout(aboutTabPanel);
        aboutTabPanel.setLayout(aboutTabPanelLayout);
        aboutTabPanelLayout.setHorizontalGroup(
            aboutTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutTabPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        aboutTabPanelLayout.setVerticalGroup(
            aboutTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutTabPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        cardPanel.add(aboutTabPanel, "card6");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bgPanel.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 810, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        ExitPanel.setBackground(new Color(108,88,141));
    }//GEN-LAST:event_exitLabelMouseEntered

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        ExitPanel.setBackground(new Color(85,55,118));
    }//GEN-LAST:event_exitLabelMouseExited

    private void searchLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLabelMouseEntered
        SearchPanel.setBackground(new Color(108,88,141));
    }//GEN-LAST:event_searchLabelMouseEntered

    private void searchLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLabelMouseExited
        SearchPanel.setBackground(new Color(85,55,118));
    }//GEN-LAST:event_searchLabelMouseExited

    private void getLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getLabelMouseEntered
        GetMoviesPanel.setBackground(new Color(108,88,141));
    }//GEN-LAST:event_getLabelMouseEntered

    private void getLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getLabelMouseExited
        GetMoviesPanel.setBackground(new Color(85,55,118));
    }//GEN-LAST:event_getLabelMouseExited

    private void favLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favLabelMouseEntered
        FavouritePanel.setBackground(new Color(108,88,141));
    }//GEN-LAST:event_favLabelMouseEntered

    private void favLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favLabelMouseExited
        FavouritePanel.setBackground(new Color(85,55,118));
    }//GEN-LAST:event_favLabelMouseExited

    private void statsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsLabelMouseEntered
        StatsPanel.setBackground(new Color(108,88,141));
    }//GEN-LAST:event_statsLabelMouseEntered

    private void statsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsLabelMouseExited
        StatsPanel.setBackground(new Color(85,55,118));
    }//GEN-LAST:event_statsLabelMouseExited

    private void aboutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseClicked
        headerLabel.setText(aboutLabel.getText());
        cardPanel.removeAll();
        cardPanel.add(aboutTabPanel);
        cardPanel.repaint();
        cardPanel.revalidate();
    }//GEN-LAST:event_aboutLabelMouseClicked

    private void aboutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseEntered
        AboutPanel.setBackground(new Color(108,88,141));
    }//GEN-LAST:event_aboutLabelMouseEntered

    private void aboutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseExited
        AboutPanel.setBackground(new Color(85,55,118));
    }//GEN-LAST:event_aboutLabelMouseExited

    private void getLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getLabelMouseClicked
        headerLabel.setText(getLabel.getText());
        cardPanel.removeAll();
        cardPanel.add(getDataTabPanel);
        cardPanel.repaint();
        cardPanel.revalidate();
        
        ExtractedData importData = new ExtractedData();
        importData.deleteDataBase();
        JOptionPane.showMessageDialog(null, "Η ΔΙΑΓΡΑΦΗ ΤΗΣ ΒΑΣΗΣ ΟΛΟΚΛΗΡΩΘΗΚΕ!", "ΠΛΗΡΟΦΟΡΙΑ", JOptionPane.WARNING_MESSAGE);
        try {
            importData.fillGenreTable();
            JOptionPane.showMessageDialog(null, "Ολοκληρώθηκε η εισαγωγή τιμών στον πίνακα Genre!", "ΠΛΗΡΟΦΟΡΙΑ", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        try {
            importData.fillMovieTable();
            JOptionPane.showMessageDialog(null, "Ολοκληρώθηκε η εισαγωγή τιμών στον πίνακα Movie!", "ΠΛΗΡΟΦΟΡΙΑ", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
        } 
        
    }//GEN-LAST:event_getLabelMouseClicked

    private void favLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favLabelMouseClicked
        headerLabel.setText(favLabel.getText());
        cardPanel.removeAll();
        cardPanel.add(favouriteTabPanel);
        cardPanel.repaint();
        cardPanel.revalidate();
    }//GEN-LAST:event_favLabelMouseClicked

    private void searchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLabelMouseClicked
        headerLabel.setText(searchLabel.getText());
        cardPanel.removeAll();
        cardPanel.add(searchTabPanel);
        cardPanel.repaint();
        cardPanel.revalidate();
    }//GEN-LAST:event_searchLabelMouseClicked

    private void statsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsLabelMouseClicked
        headerLabel.setText(statsLabel.getText());
        cardPanel.removeAll();
        cardPanel.add(statsTabPanel);
        cardPanel.repaint();
        cardPanel.revalidate();
    }//GEN-LAST:event_statsLabelMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutPanel;
    private javax.swing.JPanel ExitPanel;
    private javax.swing.JPanel FavouritePanel;
    private javax.swing.JPanel GetMoviesPanel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JPanel StatsPanel;
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JPanel aboutTabPanel;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel favLabel;
    private javax.swing.JPanel favouriteTabPanel;
    private javax.swing.JPanel getDataTabPanel;
    private javax.swing.JLabel getLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JPanel searchTabPanel;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel statsLabel;
    private javax.swing.JPanel statsTabPanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
