/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myMovies;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author trapatsas
 */
public class Menu extends javax.swing.JFrame {

    FavoriteListJpaController favoriteListJpaController;
    MovieJpaController movieJpaController;
    GenreJpaController genreJpaController;
    EntityManager entityManager;
    ImagePanel bgImagePanel;
    private final String stringNoFavoriteList;
    private static final String IMG_PATH = "src/myMovies/images/dvd_store.png";
    ItemListener selectListListener;

    /**
     * Creates new form Menu
     *
     * @throws java.io.IOException
     */
    public Menu() throws IOException {
        this.stringNoFavoriteList = "Καμία";
        initComponents();
        EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("MyMoviesProjectPU");
        this.entityManager = entityManagerFactory.createEntityManager();
        this.favoriteListJpaController = new FavoriteListJpaController(entityManagerFactory);
        this.movieJpaController = new MovieJpaController(entityManagerFactory);
        this.genreJpaController = new GenreJpaController(entityManagerFactory);

        this.selectListListener = (ItemEvent e) -> {

            if (addToListComboBox.getSelectedItem() != null && searchResultTable.getRowCount() > 0) {

                try {
                    Object selectedValue = searchResultTable.getValueAt(searchResultTable.getSelectedRow(), 4);
                    String selectedList = addToListComboBox.getSelectedItem().toString();
                    int movieId = Integer.parseInt(selectedValue.toString());

                    Movie selectedMovie = movieJpaController.findMovie(movieId);

                    FavoriteList favoriteList = null;

                    if (addToListComboBox.getSelectedItem() != null && !stringNoFavoriteList.equals(selectedList)) {

                        favoriteList = favoriteListJpaController.findFavoriteListEntities().stream().filter(
                                fl -> fl.getName().equals(selectedList)
                        ).findFirst().get();

                    }

                    selectedMovie.setFavoriteListId(favoriteList);

                    movieJpaController.edit(selectedMovie);

                    searchResultTable.setValueAt(favoriteList == null ? stringNoFavoriteList : favoriteList.getName(), searchResultTable.getSelectedRow(), 3);

                } catch (Exception ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };

        getDataLogArea.setVisible(false);

        BufferedImage bgPicture;
        bgImagePanel = new ImagePanel(new ImageIcon(IMG_PATH).getImage());
        getDataTabPanel.add(bgImagePanel);
        getDataTabPanel.revalidate();
        getDataTabPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        MyMoviesProjectPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("MyMoviesProjectPU").createEntityManager();
        favoriteListQuery = java.beans.Beans.isDesignTime() ? null : MyMoviesProjectPUEntityManager.createQuery("SELECT f.name FROM FavoriteList f");
        favoriteListList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : favoriteListQuery.getResultList();
        favoriteListQuery1 = java.beans.Beans.isDesignTime() ? null : MyMoviesProjectPUEntityManager.createQuery("SELECT f.name FROM FavoriteList f");
        favoriteListList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : favoriteListQuery1.getResultList();
        bgPanel = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        GetMoviesPanel = new javax.swing.JPanel();
        getLabel = new javax.swing.JLabel();
        FavouritePanel = new javax.swing.JPanel();
        favLabel = new javax.swing.JLabel();
        SearchPanel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        StatsPanel = new javax.swing.JPanel();
        statsLabel = new javax.swing.JLabel();
        ExitPanel = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        AboutPanel = new javax.swing.JPanel();
        aboutLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        getDataTabPanel = new javax.swing.JPanel();
        getDataLogArea = new javax.swing.JScrollPane();
        getDataLogTextArea = new javax.swing.JTextArea();
        favouriteTabPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        allFavoritesList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        favListTable = new javax.swing.JTable();
        createButton = new javax.swing.JButton();
        editListButton = new javax.swing.JButton();
        deleteListButton = new javax.swing.JButton();
        searchTabPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        GenreSearchComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        YearSearchTextField = new javax.swing.JTextField();
        searchMoviesButton = new javax.swing.JButton();
        clearΙnputsButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        addToListComboBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        searchResultTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        statsTabPanel = new javax.swing.JPanel();
        top10MoviesButton = new javax.swing.JButton();
        bestMoviePerListButton = new javax.swing.JButton();
        bestMoviesScrollPane = new javax.swing.JScrollPane();
        statsTable1 = new javax.swing.JTable();
        aboutTabPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        aboutPaneTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(108, 88, 141));
        setLocationByPlatform(true);

        bgPanel.setBackground(new java.awt.Color(108, 88, 141));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarPanel.setBackground(new java.awt.Color(54, 33, 89));
        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GetMoviesPanel.setBackground(new java.awt.Color(85, 55, 118));

        getLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getLabel.setForeground(new java.awt.Color(255, 255, 255));
        getLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_Data_Transfer_15px_1.png"))); // NOI18N
        getLabel.setLabelFor(GetMoviesPanel);
        getLabel.setText("Ανάκτηση & Αποθήκευση");
        getLabel.setToolTipText(null);
        getLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                getLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                getLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout GetMoviesPanelLayout = new javax.swing.GroupLayout(GetMoviesPanel);
        GetMoviesPanel.setLayout(GetMoviesPanelLayout);
        GetMoviesPanelLayout.setHorizontalGroup(
            GetMoviesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GetMoviesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(96, 96, 96))
        );
        GetMoviesPanelLayout.setVerticalGroup(
            GetMoviesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(getLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sidebarPanel.add(GetMoviesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, 60));

        FavouritePanel.setBackground(new java.awt.Color(85, 55, 118));

        favLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        favLabel.setForeground(new java.awt.Color(255, 255, 255));
        favLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        favLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_Heart_15px.png"))); // NOI18N
        favLabel.setLabelFor(FavouritePanel);
        favLabel.setText("Λίστες Αγαπημένων");
        favLabel.setToolTipText(null);
        favLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                favLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                favLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                favLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout FavouritePanelLayout = new javax.swing.GroupLayout(FavouritePanel);
        FavouritePanel.setLayout(FavouritePanelLayout);
        FavouritePanelLayout.setHorizontalGroup(
            FavouritePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FavouritePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(favLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        FavouritePanelLayout.setVerticalGroup(
            FavouritePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(favLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sidebarPanel.add(FavouritePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 200, 60));

        SearchPanel.setBackground(new java.awt.Color(85, 55, 118));

        searchLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchLabel.setForeground(new java.awt.Color(255, 255, 255));
        searchLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        searchLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_Search_15px.png"))); // NOI18N
        searchLabel.setLabelFor(SearchPanel);
        searchLabel.setText("Αναζήτηση ταινιών");
        searchLabel.setToolTipText(null);
        searchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchLabelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sidebarPanel.add(SearchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 60));

        StatsPanel.setBackground(new java.awt.Color(85, 55, 118));

        statsLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        statsLabel.setForeground(new java.awt.Color(255, 255, 255));
        statsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_Combo_Chart_15px.png"))); // NOI18N
        statsLabel.setLabelFor(StatsPanel);
        statsLabel.setText("Στατιστικά");
        statsLabel.setToolTipText(null);
        statsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statsLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                statsLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                statsLabelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout StatsPanelLayout = new javax.swing.GroupLayout(StatsPanel);
        StatsPanel.setLayout(StatsPanelLayout);
        StatsPanelLayout.setHorizontalGroup(
            StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        StatsPanelLayout.setVerticalGroup(
            StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sidebarPanel.add(StatsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 200, 60));

        ExitPanel.setBackground(new java.awt.Color(85, 55, 118));

        exitLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        exitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_Shutdown_15px.png"))); // NOI18N
        exitLabel.setLabelFor(ExitPanel);
        exitLabel.setText("Έξοδος");
        exitLabel.setToolTipText(null);
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ExitPanelLayout = new javax.swing.GroupLayout(ExitPanel);
        ExitPanel.setLayout(ExitPanelLayout);
        ExitPanelLayout.setHorizontalGroup(
            ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        ExitPanelLayout.setVerticalGroup(
            ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sidebarPanel.add(ExitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 200, 60));

        AboutPanel.setBackground(new java.awt.Color(85, 55, 118));

        aboutLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aboutLabel.setForeground(new java.awt.Color(255, 255, 255));
        aboutLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        aboutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_About_15px.png"))); // NOI18N
        aboutLabel.setLabelFor(AboutPanel);
        aboutLabel.setText("Σχετικά");
        aboutLabel.setToolTipText(null);
        aboutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout AboutPanelLayout = new javax.swing.GroupLayout(AboutPanel);
        AboutPanel.setLayout(AboutPanelLayout);
        AboutPanelLayout.setHorizontalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        AboutPanelLayout.setVerticalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sidebarPanel.add(AboutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 200, 60));

        jLabel6.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("My Movies");
        sidebarPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 120, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_Disney_Movies__100px.png"))); // NOI18N
        jLabel7.setToolTipText("");
        sidebarPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 100, 40));

        bgPanel.add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        topPanel.setBackground(new java.awt.Color(108, 88, 141));
        topPanel.setPreferredSize(new java.awt.Dimension(810, 600));

        HeaderPanel.setBackground(new java.awt.Color(54, 33, 89));

        headerLabel.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(204, 204, 204));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setLabelFor(HeaderPanel);
        headerLabel.setToolTipText(null);

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cardPanel.setBackground(new java.awt.Color(108, 88, 141));
        cardPanel.setLayout(new java.awt.CardLayout());

        getDataTabPanel.setBackground(new java.awt.Color(108, 88, 141));

        getDataLogArea.setBackground(new java.awt.Color(108, 88, 141));
        getDataLogArea.setForeground(new java.awt.Color(255, 255, 255));
        getDataLogArea.setToolTipText("");

        getDataLogTextArea.setEditable(false);
        getDataLogTextArea.setBackground(new java.awt.Color(108, 88, 141));
        getDataLogTextArea.setColumns(20);
        getDataLogTextArea.setForeground(new java.awt.Color(255, 255, 255));
        getDataLogTextArea.setRows(5);
        getDataLogTextArea.setBorder(null);
        getDataLogArea.setViewportView(getDataLogTextArea);

        javax.swing.GroupLayout getDataTabPanelLayout = new javax.swing.GroupLayout(getDataTabPanel);
        getDataTabPanel.setLayout(getDataTabPanelLayout);
        getDataTabPanelLayout.setHorizontalGroup(
            getDataTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getDataTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getDataLogArea, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                .addContainerGap())
        );
        getDataTabPanelLayout.setVerticalGroup(
            getDataTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getDataTabPanelLayout.createSequentialGroup()
                .addComponent(getDataLogArea, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardPanel.add(getDataTabPanel, "card2");

        favouriteTabPanel.setBackground(new java.awt.Color(108, 88, 141));

        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, favoriteListList, allFavoritesList);
        bindingGroup.addBinding(jListBinding);

        allFavoritesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                allFavoritesListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(allFavoritesList);

        favListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Τίτλος ταινίας", "Βαθμολογία", "Περιγραφή"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(favListTable);

        createButton.setText("Δημιουργία");
        createButton.setToolTipText("");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        editListButton.setText("Επεξεργασία");
        editListButton.setToolTipText("");
        editListButton.setEnabled(false);
        editListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editListButtonActionPerformed(evt);
            }
        });

        deleteListButton.setText("Διαγραφή");
        deleteListButton.setToolTipText("");
        deleteListButton.setEnabled(false);
        deleteListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout favouriteTabPanelLayout = new javax.swing.GroupLayout(favouriteTabPanel);
        favouriteTabPanel.setLayout(favouriteTabPanelLayout);
        favouriteTabPanelLayout.setHorizontalGroup(
            favouriteTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(favouriteTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(favouriteTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(favouriteTabPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(favouriteTabPanelLayout.createSequentialGroup()
                        .addComponent(createButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editListButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteListButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        favouriteTabPanelLayout.setVerticalGroup(
            favouriteTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, favouriteTabPanelLayout.createSequentialGroup()
                .addGroup(favouriteTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(editListButton)
                    .addComponent(deleteListButton))
                .addGap(18, 18, 18)
                .addGroup(favouriteTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardPanel.add(favouriteTabPanel, "card3");

        searchTabPanel.setBackground(new java.awt.Color(108, 88, 141));
        searchTabPanel.setPreferredSize(new java.awt.Dimension(810, 525));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Είδος Ταινίας :");

        GenreSearchComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Είδος", "Action", "Romance", "Science Fiction" }));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Έτος κυκλοφορίας :");

        YearSearchTextField.setText("Έτος");

        searchMoviesButton.setText("Αναζήτηση");
        searchMoviesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMoviesButtonActionPerformed(evt);
            }
        });

        clearΙnputsButton.setText("Καθαρισμός Κριτηρίων");
        clearΙnputsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearΙnputsButtonActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Προσθήκη σε λίστα");

        searchResultTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Τίτλος Ταινίας", "Βαθμολογία", "Περιγραφή"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        searchResultTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(searchResultTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Κριτήρια αναζήτησης");

        javax.swing.GroupLayout searchTabPanelLayout = new javax.swing.GroupLayout(searchTabPanel);
        searchTabPanel.setLayout(searchTabPanelLayout);
        searchTabPanelLayout.setHorizontalGroup(
            searchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addToListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(searchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(searchTabPanelLayout.createSequentialGroup()
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(searchTabPanelLayout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(searchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(GenreSearchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(YearSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(searchMoviesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clearΙnputsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(searchTabPanelLayout.createSequentialGroup()
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        searchTabPanelLayout.setVerticalGroup(
            searchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTabPanelLayout.createSequentialGroup()
                .addGroup(searchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchTabPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(searchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GenreSearchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(YearSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(searchMoviesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearΙnputsButton)
                        .addGap(49, 49, 49)
                        .addGroup(searchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addToListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchTabPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        cardPanel.add(searchTabPanel, "card4");

        statsTabPanel.setBackground(new java.awt.Color(108, 88, 141));

        top10MoviesButton.setText("Οι 10 Καλύτερες Ταινίες");
        top10MoviesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                top10MoviesButtonActionPerformed(evt);
            }
        });

        bestMoviePerListButton.setText("Οι Καλύτερες Ταινίες ανά Λίστα");
        bestMoviePerListButton.setToolTipText("");
        bestMoviePerListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestMoviePerListButtonActionPerformed(evt);
            }
        });

        statsTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Τίτλος ταινίας", "Βαθμολογία"
            }
        ));
        bestMoviesScrollPane.setViewportView(statsTable1);

        javax.swing.GroupLayout statsTabPanelLayout = new javax.swing.GroupLayout(statsTabPanel);
        statsTabPanel.setLayout(statsTabPanelLayout);
        statsTabPanelLayout.setHorizontalGroup(
            statsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsTabPanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(statsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bestMoviesScrollPane)
                    .addGroup(statsTabPanelLayout.createSequentialGroup()
                        .addComponent(top10MoviesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bestMoviePerListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        statsTabPanelLayout.setVerticalGroup(
            statsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsTabPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(statsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bestMoviePerListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(top10MoviesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bestMoviesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        cardPanel.add(statsTabPanel, "card5");

        aboutTabPanel.setBackground(new java.awt.Color(108, 88, 141));
        aboutTabPanel.setForeground(new java.awt.Color(108, 88, 141));
        aboutTabPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jScrollPane1.setBorder(null);

        aboutPaneTextArea.setEditable(false);
        aboutPaneTextArea.setBackground(new java.awt.Color(108, 88, 141));
        aboutPaneTextArea.setColumns(20);
        aboutPaneTextArea.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        aboutPaneTextArea.setForeground(new java.awt.Color(255, 255, 255));
        aboutPaneTextArea.setRows(5);
        aboutPaneTextArea.setText("Η εφαρμογή αυτή δημιουργήθηκε από τους φοιτητές \ni) Παναγιώτη Τραπάτσα\nii) Αποστόλη Νταλαμπίρα και \niii) Δημήτρη Τομπέα\nστα πλαίσια της 3ης ομαδικής εργασίας για την ΠΛΗ24,\nμε επιβλέπων καθηγητή τον κ. Φιτσιλή Παναγιώτη\n");
        aboutPaneTextArea.setBorder(null);
        jScrollPane1.setViewportView(aboutPaneTextArea);

        javax.swing.GroupLayout aboutTabPanelLayout = new javax.swing.GroupLayout(aboutTabPanel);
        aboutTabPanel.setLayout(aboutTabPanelLayout);
        aboutTabPanelLayout.setHorizontalGroup(
            aboutTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutTabPanelLayout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        aboutTabPanelLayout.setVerticalGroup(
            aboutTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutTabPanelLayout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );

        cardPanel.add(aboutTabPanel, "card6");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bgPanel.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 810, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bestMoviePerListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestMoviePerListButtonActionPerformed

        List<Movie> topMovies = this.movieJpaController.findMovieEntities();
        Collections.sort(topMovies, Collections.reverseOrder(Comparator.comparing(Movie::getRating)));

        List<FavoriteList> favoriteLists = favoriteListJpaController.findFavoriteListEntities();

        DefaultTableModel bestMoviesModel2 = new DefaultTableModel();
        bestMoviesModel2.setColumnIdentifiers(new String[]{"Λίστα αγαπημένων", "Τίτλος ταινίας"});

        for (Movie m : topMovies) {
            if (favoriteLists.contains(m.getFavoriteListId())) {
                favoriteLists.remove(m.getFavoriteListId());
                bestMoviesModel2.addRow(new String[]{m.getFavoriteListId().getName(), m.getTitle()});
            }
            if (favoriteLists.isEmpty()) {
                break;
            }
        }
        statsTable1.setModel(bestMoviesModel2);
    }//GEN-LAST:event_bestMoviePerListButtonActionPerformed

    private void top10MoviesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_top10MoviesButtonActionPerformed
        // αφορά το button που επιστρέφει τις δέκα (10) καλύτερες βάση βαθμολογίας ταινίες//

        List<Movie> topMovies = this.movieJpaController.findMovieEntities();
        Collections.sort(topMovies, Collections.reverseOrder(Comparator.comparing(Movie::getRating)));
        List<Movie> topTenMovies = topMovies.subList(0, 10);

        //bestMoviesModel
        DefaultTableModel bestMoviesModel = new DefaultTableModel();
        bestMoviesModel.setColumnIdentifiers(new String[]{"Τίτλος ταινίας", "Βαθμολογία"});

        //for loop στην λίστα και πρόσθεση των ταινιών στο model μου
        topTenMovies.forEach(movie
                -> bestMoviesModel.addRow(
                        new String[]{movie.getTitle(), Float.toString(movie.getRating())}
                )
        );
        //εμφάνιση του ΤΑΒLE
        statsTable1.setModel(bestMoviesModel);
    }//GEN-LAST:event_top10MoviesButtonActionPerformed

    private void clearΙnputsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearΙnputsButtonActionPerformed
        GenreSearchComboBox.removeAllItems();
        GenreSearchComboBox.addItem("Είδος");
        GenreSearchComboBox.addItem("Action");
        GenreSearchComboBox.addItem("Romance");
        GenreSearchComboBox.addItem("Science Fiction");
        GenreSearchComboBox.setSelectedIndex(0);

        YearSearchTextField.setText("Έτος");

        DefaultTableModel defTableModel = new DefaultTableModel();

        searchResultTable.setModel(defTableModel);
    }//GEN-LAST:event_clearΙnputsButtonActionPerformed

    private void searchMoviesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMoviesButtonActionPerformed
        // TODO add your handling code here:
        String selectedYear = YearSearchTextField.getText();
        String selectedGenre = GenreSearchComboBox.getSelectedItem().toString();

        List<Movie> movieList = this.movieJpaController.findMovieEntities();

        SimpleDateFormat yearDateFormat = new SimpleDateFormat("yyyy");

        // Names of columns
        Vector<String> columnNames = new Vector<>();
        columnNames.add("Τίτλος ταινίας");
        columnNames.add("Βαθμολογία");
        columnNames.add("Περιγραφή");
        columnNames.add("Λίστα");
        columnNames.add("Id");

        // Data of the table
        Vector<Vector<Object>> data = new Vector<>();

        movieList.stream().filter(
                movie -> selectedGenre.equals(movie.getGenreId().getName())
                && selectedYear.equals(yearDateFormat.format(movie.getReleaseDate()))
        ).map((movie) -> {
            Vector<Object> vector = new Vector<>();
            vector.add(movie.getTitle());
            vector.add(movie.getRating());
            vector.add(movie.getOverview());
            vector.add(movie.getFavoriteListId() == null ? stringNoFavoriteList : movie.getFavoriteListId().getName());
            vector.add(movie.getId());
            return vector;
        }).forEachOrdered((vector) -> {
            data.add(vector);
        });

        DefaultTableModel defTableModel = new DefaultTableModel();
        defTableModel.setDataVector(data, columnNames);

        searchResultTable.setModel(defTableModel);

        TableColumn listCol = searchResultTable.getColumnModel().getColumn(3);
        TableColumn mIdCol = searchResultTable.getColumnModel().getColumn(4);

        listCol.setMinWidth(0);
        listCol.setMaxWidth(0);
        listCol.setResizable(false);

        mIdCol.setMinWidth(0);
        mIdCol.setMaxWidth(0);
        mIdCol.setResizable(false);

        TableRowSorter<TableModel> sorter = new TableRowSorter<>(searchResultTable.getModel());
        searchResultTable.setRowSorter(sorter);
        List<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);

        attachSearchTableListener();

        addToListComboBox.addItemListener(selectListListener);
    }//GEN-LAST:event_searchMoviesButtonActionPerformed

    private void deleteListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteListButtonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Θέλετε να διαγράψετε τις λίστες οριστικά?", "ΔΙΑΓΡΑΦΗ ΛΙΣΤΩΝ", JOptionPane.YES_NO_OPTION);

        if (confirm == 0) {
            try {
                List<String> listToDelete = allFavoritesList.getSelectedValuesList();
                List<FavoriteList> listsToDelete = this.favoriteListJpaController.findFavoriteListEntities().stream().filter(l -> listToDelete.contains(l.getName())).collect(Collectors.toList());

                List<Movie> moviesToReset = this.movieJpaController.findMovieEntities().stream().filter(movie -> listsToDelete.contains(movie.getFavoriteListId())).collect(Collectors.toList());

                for (Movie m : moviesToReset) {
                    m.setFavoriteListId(null);
                    this.movieJpaController.edit(m);
                }

                for (FavoriteList l : listsToDelete) {
                    this.favoriteListJpaController.destroy(l.getId());
                }
            } catch (Exception ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        updateFavouritesList();
    }//GEN-LAST:event_deleteListButtonActionPerformed

    private void editListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editListButtonActionPerformed
        EditFavouriteListJDialog sForm = new EditFavouriteListJDialog(null, false, allFavoritesList);
        sForm.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        sForm.pack();
        sForm.setLocationRelativeTo(createButton);

        sForm.setVisible(true);
    }//GEN-LAST:event_editListButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        NewFavouriteListJDialog sForm = new NewFavouriteListJDialog(null, false, allFavoritesList);
        sForm.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        sForm.pack();
        sForm.setLocationRelativeTo(createButton);

        sForm.setVisible(true);
    }//GEN-LAST:event_createButtonActionPerformed

    private void allFavoritesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_allFavoritesListValueChanged
        if (allFavoritesList.getSelectedValue() != null) {

            editListButton.setEnabled(true);
            deleteListButton.setEnabled(true);
            DefaultTableModel defTableModel = new DefaultTableModel();
            List<Movie> movieList = this.movieJpaController.findMovieEntities();

            String listSelection = allFavoritesList.getSelectedValue();

            // Names of columns
            Vector<String> columnNames = new Vector<String>();
            columnNames.add("Τίτλος ταινίας");
            columnNames.add("Βαθμολογία");
            columnNames.add("Περιγραφή");

            // Data of the table
            Vector<Vector<Object>> data = new Vector<>();

            movieList.stream().filter(
                    movie -> listSelection.equals(movie.getFavoriteListId() == null ? "" : movie.getFavoriteListId().getName())
            ).map((movie) -> {
                Vector<Object> vector = new Vector<>();
                vector.add(movie.getTitle());
                vector.add(movie.getRating());
                vector.add(movie.getOverview());
                return vector;
            }).forEachOrdered((vector) -> {
                data.add(vector);
            });

            defTableModel.setDataVector(data, columnNames);
            favListTable.setModel(defTableModel);
        } else {
            editListButton.setEnabled(false);
            deleteListButton.setEnabled(false);
        }
    }//GEN-LAST:event_allFavoritesListValueChanged

    private void aboutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseExited
        AboutPanel.setBackground(new Color(85, 55, 118));
    }//GEN-LAST:event_aboutLabelMouseExited

    private void aboutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseEntered
        AboutPanel.setBackground(new Color(108, 88, 141));
    }//GEN-LAST:event_aboutLabelMouseEntered

    private void aboutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseClicked
        headerLabel.setText(aboutLabel.getText());
        cardPanel.removeAll();
        cardPanel.add(aboutTabPanel);
        cardPanel.repaint();
        cardPanel.revalidate();
    }//GEN-LAST:event_aboutLabelMouseClicked

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        ExitPanel.setBackground(new Color(85, 55, 118));
    }//GEN-LAST:event_exitLabelMouseExited

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        ExitPanel.setBackground(new Color(108, 88, 141));
    }//GEN-LAST:event_exitLabelMouseEntered

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void statsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsLabelMouseExited
        StatsPanel.setBackground(new Color(85, 55, 118));
    }//GEN-LAST:event_statsLabelMouseExited

    private void statsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsLabelMouseEntered
        StatsPanel.setBackground(new Color(108, 88, 141));
    }//GEN-LAST:event_statsLabelMouseEntered

    private void statsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsLabelMouseClicked
        headerLabel.setText(statsLabel.getText());
        cardPanel.removeAll();
        cardPanel.add(statsTabPanel);
        cardPanel.repaint();
        cardPanel.revalidate();
    }//GEN-LAST:event_statsLabelMouseClicked

    private void searchLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLabelMouseEntered
        SearchPanel.setBackground(new Color(108, 88, 141));
    }//GEN-LAST:event_searchLabelMouseEntered

    private void searchLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLabelMouseExited
        SearchPanel.setBackground(new Color(85, 55, 118));
    }//GEN-LAST:event_searchLabelMouseExited

    private void searchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLabelMouseClicked
        headerLabel.setText(searchLabel.getText());
        cardPanel.removeAll();
        cardPanel.add(searchTabPanel);
        cardPanel.repaint();
        cardPanel.revalidate();

        addToListComboBox.removeItemListener(this.selectListListener);

        DefaultTableModel defTableModel = new DefaultTableModel();

        defTableModel.setRowCount(0);

        searchResultTable.setModel(defTableModel);

        addToListComboBox.removeAllItems();
        addToListComboBox.addItem(stringNoFavoriteList);
        this.favoriteListJpaController.findFavoriteListEntities().forEach((favoriteList) -> {
            addToListComboBox.addItem(favoriteList.getName());
        });
        addToListComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_searchLabelMouseClicked

    private void favLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favLabelMouseExited
        FavouritePanel.setBackground(new Color(85, 55, 118));
    }//GEN-LAST:event_favLabelMouseExited

    private void favLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favLabelMouseEntered
        FavouritePanel.setBackground(new Color(108, 88, 141));
    }//GEN-LAST:event_favLabelMouseEntered

    private void favLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favLabelMouseClicked
        headerLabel.setText(favLabel.getText());
        cardPanel.removeAll();
        cardPanel.add(favouriteTabPanel);
        cardPanel.repaint();
        cardPanel.revalidate();
        if (allFavoritesList.getModel().getSize() > 0) {
            allFavoritesList.setSelectedIndex(0);
        }
    }//GEN-LAST:event_favLabelMouseClicked

    private void getLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getLabelMouseExited
        GetMoviesPanel.setBackground(new Color(85, 55, 118));
    }//GEN-LAST:event_getLabelMouseExited

    private void getLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getLabelMouseEntered
        GetMoviesPanel.setBackground(new Color(108, 88, 141));
    }//GEN-LAST:event_getLabelMouseEntered

    private void getLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getLabelMouseClicked
        headerLabel.setText(getLabel.getText());
        cardPanel.removeAll();
        cardPanel.add(getDataTabPanel);
        cardPanel.repaint();
        cardPanel.revalidate();

        ExtractedData importData = new ExtractedData(getDataLogTextArea);
        int confirm = JOptionPane.showConfirmDialog(null, "Θέλετε να διαγράψετε τη βάση?", "ΔΙΑΓΡΑΦΗ ΒΑΣΗΣ", JOptionPane.YES_NO_OPTION);

        if (confirm == 0) {
            getDataTabPanel.remove(this.bgImagePanel);
            getDataLogArea.setVisible(true);
            importData.deleteDataBase();
            getDataLogTextArea.append("Η ΔΙΑΓΡΑΦΗ ΤΗΣ ΒΑΣΗΣ ΟΛΟΚΛΗΡΩΘΗΚΕ!" + "\n\n");
            JOptionPane.showMessageDialog(null, "Η ΔΙΑΓΡΑΦΗ ΤΗΣ ΒΑΣΗΣ ΟΛΟΚΛΗΡΩΘΗΚΕ!", "ΠΛΗΡΟΦΟΡΙΑ", JOptionPane.WARNING_MESSAGE);
            try {
                importData.fillGenreTable();
                getDataLogTextArea.append("Ολοκληρώθηκε η εισαγωγή τιμών στον πίνακα Genre!" + "\n\n");
                JOptionPane.showMessageDialog(null, "Ολοκληρώθηκε η εισαγωγή τιμών στον πίνακα Genre!", "ΠΛΗΡΟΦΟΡΙΑ", JOptionPane.WARNING_MESSAGE);
            } catch (Exception ex) {
                getDataLogTextArea.append(ex.getMessage() + "\n\n");
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                JOptionPane.showMessageDialog(null, "Ξεκινάει η εισαγωγή ταινιών!", "ΠΛΗΡΟΦΟΡΙΑ", JOptionPane.WARNING_MESSAGE);
                importData.fillMovieTable();
                getDataLogTextArea.append("Ολοκληρώθηκε η εισαγωγή τιμών στον πίνακα Movie!" + "\n\n");
            } catch (Exception ex) {
                getDataLogTextArea.append(ex.getMessage() + "\n\n");
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(null, " Η ανάκτηση των δεδομένων ολοκληρώθηκε!", "ΠΛΗΡΟΦΟΡΙΑ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_getLabelMouseClicked

    public void updateFavouritesList() {
        List<FavoriteList> favoriteList = this.favoriteListJpaController.findFavoriteListEntities();
        DefaultListModel lm = new DefaultListModel<>();
        favoriteList.forEach(fv -> lm.addElement(fv.getName()));
        allFavoritesList.setModel(lm);
    }

    private void attachSearchTableListener() {
        searchResultTable.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            if (searchResultTable.getSelectedRow() > -1) {
                int items = addToListComboBox.getItemCount();
                for (int i = 0; i < items; i++) {
                    if (searchResultTable.getValueAt(searchResultTable.getSelectedRow(), 3).toString().equals(addToListComboBox.getItemAt(i))) {
                        addToListComboBox.setSelectedIndex(i);
                        break;
                    }
                }
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Menu().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutPanel;
    private javax.swing.JPanel ExitPanel;
    private javax.swing.JPanel FavouritePanel;
    private javax.swing.JComboBox<String> GenreSearchComboBox;
    private javax.swing.JPanel GetMoviesPanel;
    private javax.swing.JPanel HeaderPanel;
    private javax.persistence.EntityManager MyMoviesProjectPUEntityManager;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JPanel StatsPanel;
    private javax.swing.JTextField YearSearchTextField;
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JTextArea aboutPaneTextArea;
    private javax.swing.JPanel aboutTabPanel;
    private javax.swing.JComboBox<String> addToListComboBox;
    private javax.swing.JList<String> allFavoritesList;
    private javax.swing.JButton bestMoviePerListButton;
    private javax.swing.JScrollPane bestMoviesScrollPane;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JButton clearΙnputsButton;
    private javax.swing.JButton createButton;
    private javax.swing.JButton deleteListButton;
    private javax.swing.JButton editListButton;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel favLabel;
    private javax.swing.JTable favListTable;
    private java.util.List<myMovies.FavoriteList> favoriteListList;
    private java.util.List<myMovies.FavoriteList> favoriteListList1;
    private javax.persistence.Query favoriteListQuery;
    private javax.persistence.Query favoriteListQuery1;
    private javax.swing.JPanel favouriteTabPanel;
    private javax.swing.JScrollPane getDataLogArea;
    private javax.swing.JTextArea getDataLogTextArea;
    private javax.swing.JPanel getDataTabPanel;
    private javax.swing.JLabel getLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JButton searchMoviesButton;
    private javax.swing.JTable searchResultTable;
    private javax.swing.JPanel searchTabPanel;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel statsLabel;
    private javax.swing.JPanel statsTabPanel;
    private javax.swing.JTable statsTable1;
    private javax.swing.JButton top10MoviesButton;
    private javax.swing.JPanel topPanel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
