/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myMovies;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author trapatsas
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        GetMoviesPanel = new javax.swing.JPanel();
        getLabel = new javax.swing.JLabel();
        FavouritePanel = new javax.swing.JPanel();
        favLabel = new javax.swing.JLabel();
        SearchPanel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        StatsPanel = new javax.swing.JPanel();
        statsLabel = new javax.swing.JLabel();
        ExitPanel = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        AboutPanel = new javax.swing.JPanel();
        aboutLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(108, 88, 141));
        setLocationByPlatform(true);

        bgPanel.setBackground(new java.awt.Color(108, 88, 141));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarPanel.setBackground(new java.awt.Color(54, 33, 89));
        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GetMoviesPanel.setBackground(new java.awt.Color(85, 55, 118));

        getLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getLabel.setForeground(new java.awt.Color(255, 255, 255));
        getLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_Data_Transfer_15px_1.png"))); // NOI18N
        getLabel.setLabelFor(GetMoviesPanel);
        getLabel.setText("Ανάκτηση & Αποθήκευση");
        getLabel.setToolTipText(null);
        getLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                getLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                getLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout GetMoviesPanelLayout = new javax.swing.GroupLayout(GetMoviesPanel);
        GetMoviesPanel.setLayout(GetMoviesPanelLayout);
        GetMoviesPanelLayout.setHorizontalGroup(
            GetMoviesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GetMoviesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(96, 96, 96))
        );
        GetMoviesPanelLayout.setVerticalGroup(
            GetMoviesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(getLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sidebarPanel.add(GetMoviesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, 60));

        FavouritePanel.setBackground(new java.awt.Color(85, 55, 118));

        favLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        favLabel.setForeground(new java.awt.Color(255, 255, 255));
        favLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        favLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_Heart_15px.png"))); // NOI18N
        favLabel.setLabelFor(FavouritePanel);
        favLabel.setText("Λίστες Αγαπημένων");
        favLabel.setToolTipText(null);
        favLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                favLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                favLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout FavouritePanelLayout = new javax.swing.GroupLayout(FavouritePanel);
        FavouritePanel.setLayout(FavouritePanelLayout);
        FavouritePanelLayout.setHorizontalGroup(
            FavouritePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FavouritePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(favLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        FavouritePanelLayout.setVerticalGroup(
            FavouritePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(favLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sidebarPanel.add(FavouritePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 200, 60));

        SearchPanel.setBackground(new java.awt.Color(85, 55, 118));

        searchLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchLabel.setForeground(new java.awt.Color(255, 255, 255));
        searchLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        searchLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_Search_15px.png"))); // NOI18N
        searchLabel.setLabelFor(SearchPanel);
        searchLabel.setText("Αναζήτηση ταινιών");
        searchLabel.setToolTipText(null);
        searchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sidebarPanel.add(SearchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 60));

        StatsPanel.setBackground(new java.awt.Color(85, 55, 118));

        statsLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        statsLabel.setForeground(new java.awt.Color(255, 255, 255));
        statsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_Combo_Chart_15px.png"))); // NOI18N
        statsLabel.setLabelFor(StatsPanel);
        statsLabel.setText("Στατιστικά");
        statsLabel.setToolTipText(null);
        statsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                statsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                statsLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout StatsPanelLayout = new javax.swing.GroupLayout(StatsPanel);
        StatsPanel.setLayout(StatsPanelLayout);
        StatsPanelLayout.setHorizontalGroup(
            StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        StatsPanelLayout.setVerticalGroup(
            StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sidebarPanel.add(StatsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 200, 60));

        ExitPanel.setBackground(new java.awt.Color(85, 55, 118));

        exitLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        exitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_Shutdown_15px.png"))); // NOI18N
        exitLabel.setLabelFor(ExitPanel);
        exitLabel.setText("Έξοδος");
        exitLabel.setToolTipText(null);
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ExitPanelLayout = new javax.swing.GroupLayout(ExitPanel);
        ExitPanel.setLayout(ExitPanelLayout);
        ExitPanelLayout.setHorizontalGroup(
            ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        ExitPanelLayout.setVerticalGroup(
            ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sidebarPanel.add(ExitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 200, 60));

        AboutPanel.setBackground(new java.awt.Color(85, 55, 118));

        aboutLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aboutLabel.setForeground(new java.awt.Color(255, 255, 255));
        aboutLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        aboutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_About_15px.png"))); // NOI18N
        aboutLabel.setLabelFor(AboutPanel);
        aboutLabel.setText("Σχετικά");
        aboutLabel.setToolTipText(null);
        aboutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout AboutPanelLayout = new javax.swing.GroupLayout(AboutPanel);
        AboutPanel.setLayout(AboutPanelLayout);
        AboutPanelLayout.setHorizontalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        AboutPanelLayout.setVerticalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sidebarPanel.add(AboutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 200, 60));

        jLabel6.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("My Movies");
        sidebarPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myMovies/images/icons8_Disney_Movies__100px.png"))); // NOI18N
        jLabel7.setToolTipText("");
        sidebarPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 100, 40));

        bgPanel.add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        topPanel.setBackground(new java.awt.Color(108, 88, 141));
        topPanel.setPreferredSize(new java.awt.Dimension(810, 600));

        HeaderPanel.setBackground(new java.awt.Color(54, 33, 89));

        headerLabel.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(204, 204, 204));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setLabelFor(HeaderPanel);
        headerLabel.setToolTipText(null);

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
                .addContainerGap())
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(500, Short.MAX_VALUE))
        );

        bgPanel.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 810, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        ExitPanel.setBackground(new Color(108,88,141));
    }//GEN-LAST:event_exitLabelMouseEntered

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        ExitPanel.setBackground(new Color(85,55,118));
    }//GEN-LAST:event_exitLabelMouseExited

    private void searchLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLabelMouseEntered
        SearchPanel.setBackground(new Color(108,88,141));
    }//GEN-LAST:event_searchLabelMouseEntered

    private void searchLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLabelMouseExited
        SearchPanel.setBackground(new Color(85,55,118));
    }//GEN-LAST:event_searchLabelMouseExited

    private void getLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getLabelMouseEntered
        GetMoviesPanel.setBackground(new Color(108,88,141));
    }//GEN-LAST:event_getLabelMouseEntered

    private void getLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getLabelMouseExited
        GetMoviesPanel.setBackground(new Color(85,55,118));
    }//GEN-LAST:event_getLabelMouseExited

    private void favLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favLabelMouseEntered
        FavouritePanel.setBackground(new Color(108,88,141));
    }//GEN-LAST:event_favLabelMouseEntered

    private void favLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favLabelMouseExited
        FavouritePanel.setBackground(new Color(85,55,118));
    }//GEN-LAST:event_favLabelMouseExited

    private void statsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsLabelMouseEntered
        StatsPanel.setBackground(new Color(108,88,141));
    }//GEN-LAST:event_statsLabelMouseEntered

    private void statsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsLabelMouseExited
        StatsPanel.setBackground(new Color(85,55,118));
    }//GEN-LAST:event_statsLabelMouseExited

    private void aboutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseClicked
        headerLabel.setText(aboutLabel.getText());
    }//GEN-LAST:event_aboutLabelMouseClicked

    private void aboutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseEntered
        AboutPanel.setBackground(new Color(108,88,141));
    }//GEN-LAST:event_aboutLabelMouseEntered

    private void aboutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseExited
        AboutPanel.setBackground(new Color(85,55,118));
    }//GEN-LAST:event_aboutLabelMouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutPanel;
    private javax.swing.JPanel ExitPanel;
    private javax.swing.JPanel FavouritePanel;
    private javax.swing.JPanel GetMoviesPanel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JPanel StatsPanel;
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel favLabel;
    private javax.swing.JLabel getLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel statsLabel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
